### ISSUE TITLE
Prayer - Bones

### ISSUE THREAD

**Issue by Chanizu** [Open-RSC/Game#83] opened 2018-07-15 21:26 UTC
Bones award less exp than intended.

We tried burying x amount of bones in-game.
1 bone = 3 exp in skill
2 bones = 7 exp in skill
3 bones = 10 exp in skill
4 bones = 14 exp in skill

Bones are meant to give 3,75 exp each which results in
1 bone = 3
2 bones = 7
3 bones = 11
4 bones = 15

Most likely the bones currently give 3,5 instead of the intended 3,75.

**Comment by Kenix3** [comment] 2018-07-15 21:37
Unable to replicate. I did verify that bones give 15 real EXP as intended. Perhaps you started at a higher EXP?

Believe this was already fixed by #53

**Closed by Kenix3** 2018-07-15 21:37 UTC
