### ISSUE TITLE
Cannot pick up sleeping bag on table in Lumbridge's eastern chicken farm

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#329] opened 2018-08-14 13:54 UTC
Submitted by Discord user: Reinhard

Perhaps this is because there was an update a few days ago that made it so you can't pick up things farther away than the tile you're on, so you're unable to take things off tables now. Or at least this specific table.

**Comment by Marwolf** [comment] 2018-08-14 14:03
duplicate of #277

**Closed by Marwolf** 2018-08-14 14:03 UTC
