### ISSUE TITLE
Wilderness NPCs slow to attack/not aggressive enough

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1075] opened 2018-11-02 19:25 UTC
Submitted by Discord user: Millz

Stand near a lot of low level wilderness NPCs (i.e. dark wizards or something) and watch how slow the NPCs are to attack. It should be one after the other with barely any break. You can stand near them for a few seconds currently without anything attacking you despite standing right next to them.

**Comment by ipkpjersi** [comment] 2018-11-08 14:49
This appears to be a duplicate of #977

**Closed** 2018-11-08 14:51 UTC
Labels: duplicate
