### ISSUE TITLE
Picking wheat will pick until inventory is full

### ISSUE THREAD

**Issue by Tessalicious** [Open-RSC/Game#320] opened 2018-08-13 13:47 UTC
**Describe the bug**
When trying to pick wheat from the field with right click it will keep adding wheat to the inventory until it's full. There is no way to cancel this and the character is frozen until the inventory is full.

**To Reproduce**
1. Go to a random wheat field
2. Right click on wheat -> pick wheat

**Expected behavior**
It should only pick 1 wheat at a time

**Comment by Christofosho** [comment] 2018-08-14 15:52
Consistent with the "Pick All" menu option config

**Comment by Kenix3** [comment] 2018-08-15 17:40
Duplicate of #354

**Closed by Kenix3** 2018-08-15 17:40 UTC
Labels: duplicate
