### ISSUE TITLE
Can pick up lines of cabbage from increasingly far away

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#260] opened 2018-08-11 06:37 UTC
**To Reproduce**
1. Go to any cabbage field
2. Click on a cabbage (first one, you'll be over it to pick it up)
3. Click on another cabbage in the same row or column (you'll be 1 square away when you pick up)
4. Click on another cabbage in the same row or column (you'll be 2 squares away when you pick up)
5. Click on another cabbage in the same row or column (you'll be 3 squares away when you pick up)
6. Click on another cabbage in the same row or column (you'll be 4 squares away when you pick up)
7. ...

**Expected behavior**
Must always be over an item to pick it up, unless you are unable to path to the item. In that case you are allowed to pick up the item from 1 tile away

-----

Also works for any other items the player drops, just that it's set up perfectly for the cabbage fields...

**Comment by Marwolf** [comment] 2018-08-11 11:02
Duplicate of #151 
Fixed in 73e67acf2c2ad19dbd1d0d83e3ad40cb6bb5162b

Appears working correctly in dev test server world.

**Closed by Marwolf** 2018-08-11 11:02 UTC
Labels: duplicate
