### ISSUE TITLE
config_table_def_cooking missing data

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#92] opened 2018-07-16 17:20 UTC
Cooking table is missing the following foods:
Ugthanki Kebab
all gnome cousine
Cooked Oomlie meat Parcel
not sure if gnome drinks are counted on this

Wiki has all data for them.

**Comment by Kenix3** [comment] 2018-07-16 18:02
Duplicate of #62

**Closed by Kenix3** 2018-07-16 18:02 UTC
Labels: bug, duplicate
