### ISSUE TITLE
Banking on android 

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1460] opened 2019-01-02 17:40 UTC
Submitted by Discord user: Kittycatrock (jenny) 

When trying to bank on the android client, the bank window immediately closes after being opened unless you hold down your finger on the screen as it is being opened. This has been a bug for a while now but wasn't a big deal when quick banking was in place since it didn't have that issue.

**Comment by Marwolf** [comment] 2019-01-08 17:08
Duplicate of #1386

**Closed by Marwolf** 2019-01-08 17:08 UTC
Labels: bug
