### ISSUE TITLE
Fishing/Cooking is Batched

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#316] opened 2018-08-13 07:07 UTC
**Describe the bug**
When fishing trout, or cooking trout, each action is completed once for each 10 levels you are in the skill. So at 30 fishing, it will complete 3 actions for one click of the mouse.

**Expected behavior**
Actions only happen once per click

**Additional context**

**Comment by Kenix3** [comment] 2018-08-15 17:40
Duplicate of #354

**Closed by Kenix3** 2018-08-15 17:40 UTC
Labels: duplicate
