### ISSUE TITLE
kbd dies in 1 hit

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#611] opened 2018-09-11 01:32 UTC
Submitted by Discord user: clive

somehow the king black dragon dies in 1 hit whatsoever. kindly check and address this, thanks

**Comment by Marwolf** [comment] 2018-09-11 01:37
Is this on the live game or the development test server with the v2.0.0 code? There is such a difference that if this is on the live game running v1 code, this is a wont-fix as it will be solved in v2.

**Comment by Marwolf** [comment] 2018-09-11 18:03
Rick IBM verified this is a V2 glitch

**Comment by multi-talented** [comment] 2018-09-11 18:13
Added kbd in lumby temp to see if different symptoms.
![kbd-lumby](https://user-images.githubusercontent.com/43180426/45378892-acb06f80-b5cc-11e8-910f-f592c970a356.jpg)

**Comment by Marwolf** [comment] 2018-09-15 10:55
Duplicate of 618

**Closed by Marwolf** 2018-09-15 10:55 UTC
Labels: duplicate
