### ISSUE TITLE
Bugs in the Shield of Arrav quest

### ISSUE THREAD

**Issue by aleclashamtaylor** [Open-RSC/Game#406] opened 2018-08-18 22:45 UTC
**Describe the bug**
After going through the quest dialogue either Katrine or Man (also known as Straven) the player is logged out automatically.

**To Reproduce**
1. Speak to Katrine (black arm gang) or Man (phoenix gang).
2. When the dialogue concludes, you will be logged out.

**Comment by Kenix3** [comment] 2018-08-19 00:14
Duplicate of #247

**Closed by Kenix3** 2018-08-19 00:14 UTC
Labels: bug
