### ISSUE TITLE
Android Banking Bug

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1469] opened 2019-01-03 19:22 UTC
Submitted by Discord user: Heather

When using Android OpenRSC to deposit/withdraw from a banker it goes through the usual banking dialogue and successfully opens the bank interface, but seconds after, the interface will automatically close. 

Therefore I cannot make any withdrawals or deposits on the Android app. :(

**Comment by Marwolf** [comment] 2019-01-08 17:08
Duplicate of #1386

**Closed by Marwolf** 2019-01-08 17:08 UTC
Labels: bug
