### ISSUE TITLE
Ranged through gate

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1317] opened 2018-12-04 02:48 UTC
Submitted by Discord user: Rixhi

Whenever you ranged NPC's through gates (safespot), it doesn't work if the NPC stands infront of you behind the gate, it will say 'I can't get a clear shot from here' in the chat, you have to stand obliquely or a weird spot to be able to shoot.

**Comment by Christofosho** [comment] 2018-12-05 22:09
Duplicate of #739

**Closed by Christofosho** 2018-12-05 22:09 UTC
