### ISSUE TITLE
Decouple Plugins From Handlers

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#1398] opened 2018-12-24 15:59 UTC
Currently our server code receives a packet from the client, and distributes it to handlers until it finds the correct one. Once it finds the correct handler, sometimes it will send the work even deeper into the code to a plugin. This is all a result of an incomplete transition from handlers to plugins. Here's what needs to happen:

1) All code that is in handlers should be ported to plugins.
2) One handler should be responsible for looking up the proper plugin to distribute to.
3) OPTIONAL (to be discussed): Make new plugins for data in other realms of the code ie: combat, fatigue

**Comment by KeplerIO** [comment] 2019-01-16 17:49
Sounds fun, what handlers do we want converted to plugins first?

**Comment by Kenix3** [comment] 2019-02-01 22:30
Duplicate of #822

**Closed by Kenix3** 2019-02-01 22:30 UTC
Labels: enhancement, help wanted
