### ISSUE TITLE
Registering accounts on android

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1415] opened 2018-12-29 17:17 UTC
Submitted by Discord user: Kittycatrock(jenny) 

Registering a new account on android pi will always result in it saying that you have made too many attempts at registering in the past hour, even if it is your first attempt. Additionally, the server will think you have registered an account correctly, making the account name and email associated with it unusable for a real registration on pc. This 'ghost account' will never work with the password you used in the initial registration.

**Comment by Marwolf** [comment] 2018-12-30 03:57
Duplicate of #1413

**Closed by Marwolf** 2018-12-30 03:57 UTC
Labels: duplicate
